[2024-05-11T18:51:33.521+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-11T18:51:33.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mysql_to_hive_all.dibimbing__position.dibimbing__position_transform_with_python manual__2024-05-11T18:09:25.933515+00:00 [queued]>
[2024-05-11T18:51:33.602+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mysql_to_hive_all.dibimbing__position.dibimbing__position_transform_with_python manual__2024-05-11T18:09:25.933515+00:00 [queued]>
[2024-05-11T18:51:33.604+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-11T18:51:33.640+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): dibimbing__position.dibimbing__position_transform_with_python> on 2024-05-11 18:09:25.933515+00:00
[2024-05-11T18:51:33.655+0000] {standard_task_runner.py:63} INFO - Started process 10324 to run task
[2024-05-11T18:51:33.676+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_mysql_to_hive_all', 'dibimbing__position.dibimbing__position_transform_with_python', 'manual__2024-05-11T18:09:25.933515+00:00', '--job-id', '929', '--raw', '--subdir', 'DAGS_FOLDER/etl_mysql_to_hive_all.py', '--cfg-path', '/tmp/tmp5_v901ft']
[2024-05-11T18:51:33.683+0000] {standard_task_runner.py:91} INFO - Job 929: Subtask dibimbing__position.dibimbing__position_transform_with_python
[2024-05-11T18:51:33.890+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_mysql_to_hive_all.dibimbing__position.dibimbing__position_transform_with_python manual__2024-05-11T18:09:25.933515+00:00 [running]> on host 94409fb18ddd
[2024-05-11T18:51:34.451+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_mysql_to_hive_all' AIRFLOW_CTX_TASK_ID='dibimbing__position.dibimbing__position_transform_with_python' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T18:09:25.933515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-11T18:09:25.933515+00:00'
[2024-05-11T18:51:34.458+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-11T18:51:34.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-11T18:51:34.461+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 33, in transform
    transformed_data = [[id+100, name.title(), position.upper()] for id, name, position in data]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_mysql_to_hive_all.py", line 33, in <listcomp>
    transformed_data = [[id+100, name.title(), position.upper()] for id, name, position in data]
                                                                     ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 1)
[2024-05-11T18:51:34.492+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_mysql_to_hive_all, task_id=dibimbing__position.dibimbing__position_transform_with_python, run_id=manual__2024-05-11T18:09:25.933515+00:00, execution_date=20240511T180925, start_date=20240511T185133, end_date=20240511T185134
[2024-05-11T18:51:34.525+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 929 for task dibimbing__position.dibimbing__position_transform_with_python (not enough values to unpack (expected 3, got 1); 10324)
[2024-05-11T18:51:34.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-11T18:51:34.602+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.11/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-11T18:51:34.640+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-11T18:51:34.648+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
